version: '3.3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - bank-network

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - mysql_db
    networks:
      - bank-network

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge

volumes:
  mysql_data:

