version: '3.3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - bank-network

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: rootpass
      DB_NAME: bankdb
    depends_on:
      - db
    networks:
      - bank-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bankdb
    volumes:
      - bank-db-data:/var/lib/mysql
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge

volumes:
  bank-db-data:
